# Generated by Django 5.0.4 on 2024-05-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('pokemon_id', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('attack_iv', models.IntegerField()),
                ('defense_iv', models.IntegerField()),
                ('stamina_iv', models.IntegerField()),
                ('shiny', models.BooleanField(default=False)),
                ('costume_id', models.IntegerField(blank=True, null=True)),
                ('lucky', models.BooleanField(default=False)),
                ('shadow', models.BooleanField(default=False)),
                ('purified', models.BooleanField(default=False)),
                ('fast_move_id', models.IntegerField(blank=True, null=True)),
                ('charged_move1_id', models.IntegerField(blank=True, null=True)),
                ('charged_move2_id', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('mirror', models.BooleanField(default=False)),
                ('friendship_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('date_caught', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('trainer_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_owned', models.BooleanField(default=True)),
                ('is_for_trade', models.BooleanField(default=False)),
                ('is_wanted', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(db_column='instance_id', on_delete=django.db.models.deletion.CASCADE, to='user_pokemon_management.pokemoninstance', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradePair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_instance', models.ForeignKey(db_column='desired_instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='desired_trades', to='user_pokemon_management.pokemoninstance')),
                ('offered_instance', models.ForeignKey(db_column='offered_instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='offered_trades', to='user_pokemon_management.pokemoninstance')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_pokemon_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('engagement_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('instance_id_from_user_1', models.ForeignKey(db_column='instance_id_from_user_1', on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user_1', to='user_pokemon_management.pokemoninstance')),
                ('instance_id_from_user_2', models.ForeignKey(db_column='instance_id_from_user_2', on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_user_2', to='user_pokemon_management.pokemoninstance')),
                ('user_1', models.ForeignKey(db_column='user_1_id', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_trades', to='user_pokemon_management.user')),
                ('user_2', models.ForeignKey(db_column='user_2_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='user_pokemon_management.user')),
            ],
        ),
        migrations.AddField(
            model_name='pokemoninstance',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_pokemon_management.user'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(check=models.Q(('is_for_trade', True), ('is_owned', True)), name='ownership_for_trade_check'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(check=models.Q(('is_for_trade', False), ('is_owned', False), ('is_wanted', True)), name='wanted_without_ownership'),
        ),
    ]
