# Generated by Django 5.0.4 on 2024-05-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pokemon_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='instance',
            field=models.OneToOneField(db_column='instance_id', on_delete=django.db.models.deletion.CASCADE, to='user_pokemon_management.pokemoninstance'),
        ),
    ]
