package pvp

import "testing"

// These matchup scores were generated by pinned PvPoke commit
// f59fc0a2c78ace0b4d3b1bdcd161880e3287e4e0. They guard the decision layer,
// not merely damage arithmetic.
func TestPvPokeOracleBuzzwoleVersusOinkologne(t *testing.T) {
	buzzwole := Fighter{
		ID: "buzzwole", Name: "Buzzwole", Types: []string{"bug", "fighting"},
		Attack: 129.86588145, Defense: 109.17012345, HP: 119,
		FastMove: Move{
			ID: "POISON_JAB", Name: "Poison Jab", Type: "poison",
			Kind: FastMove, Power: 7, EnergyGain: 7, Turns: 2,
		},
		ChargedMoves: []Move{
			{
				ID: "POWER_UP_PUNCH", Name: "Power-Up Punch", Type: "fighting",
				Kind: ChargedMove, Power: 20, EnergyCost: 35, Turns: 1,
				Buff: BuffEffect{AttackerAttack: 1, Chance: 1},
			},
			{
				ID: "SUPER_POWER", Name: "Superpower", Type: "fighting",
				Kind: ChargedMove, Power: 85, EnergyCost: 40, Turns: 1,
				Buff: BuffEffect{AttackerAttack: -1, AttackerDefense: -1, Chance: 1},
			},
		},
	}
	oinkologne := Fighter{
		ID: "oinkologne_female", Name: "Oinkologne (Female)", Types: []string{"normal"},
		Attack: 112.6369432, Defense: 108.3518421, HP: 162,
		FastMove: Move{
			ID: "MUD_SLAP", Name: "Mud Slap", Type: "ground",
			Kind: FastMove, Power: 11, EnergyGain: 10, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "BODY_SLAM", Name: "Body Slam", Type: "normal",
				Kind: ChargedMove, Power: 55, EnergyCost: 35, Turns: 1,
			},
			{
				ID: "TRAILBLAZE", Name: "Trailblaze", Type: "grass",
				Kind: ChargedMove, Power: 65, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{AttackerAttack: 1, Chance: 1},
			},
		},
	}
	want := [3][3]int{
		{915, 314, 200},
		{915, 659, 575},
		{915, 844, 575},
	}
	assertPvPokeScoreGrid(t, buzzwole, oinkologne, want)
}

func TestPvPokeOracleArcanineVersusRegisteel(t *testing.T) {
	arcanine := Fighter{
		ID: "arcanine", Name: "Arcanine", Types: []string{"fire"},
		Attack: 172.5869244022, Defense: 129.0836087471, HP: 158,
		FastMove: Move{
			ID: "SNARL", Name: "Snarl", Type: "dark",
			Kind: FastMove, Power: 5, EnergyGain: 13, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "BULLDOZE", Name: "Bulldoze", Type: "ground",
				Kind: ChargedMove, Power: 45, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{TargetDefense: -1, Chance: 0.5},
			},
			{
				ID: "CRUNCH", Name: "Crunch", Type: "dark",
				Kind: ChargedMove, Power: 70, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{TargetDefense: -1, Chance: 0.2},
			},
		},
	}
	registeel := Fighter{
		ID: "registeel", Name: "Registeel", Types: []string{"steel"},
		Attack: 126.05240237, Defense: 239.3400045, HP: 163,
		FastMove: Move{
			ID: "LOCK_ON", Name: "Lock On", Type: "normal",
			Kind: FastMove, Power: 1, EnergyGain: 5, Turns: 1,
		},
		ChargedMoves: []Move{
			{
				ID: "FLASH_CANNON", Name: "Flash Cannon", Type: "steel",
				Kind: ChargedMove, Power: 110, EnergyCost: 65, Turns: 1,
			},
			{
				ID: "FOCUS_BLAST", Name: "Focus Blast", Type: "fighting",
				Kind: ChargedMove, Power: 150, EnergyCost: 75, Turns: 1,
			},
		},
	}
	want := [3][3]int{
		{291, 190, 88},
		{556, 556, 398},
		{857, 857, 648},
	}
	assertPvPokeScoreGrid(t, arcanine, registeel, want)
}

func TestPvPokeOracleZygardeVersusGalarianCorsola(t *testing.T) {
	zygarde := Fighter{
		ID: "zygarde_50", Name: "Zygarde (50% Forme)", Types: []string{"dragon", "ground"},
		Attack: 112.7918811, Defense: 127.79630565, HP: 131,
		FastMove: Move{
			ID: "DRAGON_TAIL", Name: "Dragon Tail", Type: "dragon",
			Kind: FastMove, Power: 9, EnergyGain: 12, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "BULLDOZE", Name: "Bulldoze", Type: "ground",
				Kind: ChargedMove, Power: 45, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{TargetDefense: -1, Chance: 0.5},
			},
			{
				ID: "CRUNCH", Name: "Crunch", Type: "dark",
				Kind: ChargedMove, Power: 70, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{TargetDefense: -1, Chance: 0.2},
			},
		},
	}
	corsola := Fighter{
		ID: "corsola_galarian", Name: "Corsola (Galarian)", Types: []string{"ghost"},
		Attack: 103.5293, Defense: 155.6891, HP: 134,
		FastMove: Move{
			ID: "ASTONISH", Name: "Astonish", Type: "ghost",
			Kind: FastMove, Power: 12, EnergyGain: 10, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "NIGHT_SHADE", Name: "Night Shade", Type: "ghost",
				Kind: ChargedMove, Power: 70, EnergyCost: 45, Turns: 1,
			},
			{
				ID: "POWER_GEM", Name: "Power Gem", Type: "rock",
				Kind: ChargedMove, Power: 85, EnergyCost: 50, Turns: 1,
			},
		},
	}
	want := [3][3]int{
		{583, 380, 186},
		{751, 447, 264},
		{751, 625, 625},
	}
	assertPvPokeScoreGrid(t, zygarde, corsola, want)
}

func TestPvPokeOracleShadowQuagsireVersusGastrodon(t *testing.T) {
	quagsire := Fighter{
		ID: "quagsire_shadow", Name: "Shadow Quagsire", Types: []string{"water", "ground"},
		// Shadow modifiers belong to damage, not these base stats or CMP.
		Attack: 108.40170458320002, Defense: 112.68071970634244, HP: 164, Shadow: true,
		FastMove: Move{
			ID: "MUD_SHOT", Name: "Mud Shot", Type: "ground",
			Kind: FastMove, Power: 3, EnergyGain: 9, Turns: 2,
		},
		ChargedMoves: []Move{
			{
				ID: "AQUA_TAIL", Name: "Aqua Tail", Type: "water",
				Kind: ChargedMove, Power: 55, EnergyCost: 35, Turns: 1,
			},
			{
				ID: "MUD_BOMB", Name: "Mud Bomb", Type: "ground",
				Kind: ChargedMove, Power: 65, EnergyCost: 45, Turns: 1,
			},
		},
	}
	gastrodon := Fighter{
		ID: "gastrodon", Name: "Gastrodon", Types: []string{"water", "ground"},
		Attack: 111.74605365560001, Defense: 104.4726418792, HP: 171,
		FastMove: Move{
			ID: "MUD_SLAP", Name: "Mud Slap", Type: "ground",
			Kind: FastMove, Power: 11, EnergyGain: 10, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "BODY_SLAM", Name: "Body Slam", Type: "normal",
				Kind: ChargedMove, Power: 55, EnergyCost: 35, Turns: 1,
			},
			{
				ID: "EARTH_POWER", Name: "Earth Power", Type: "ground",
				Kind: ChargedMove, Power: 90, EnergyCost: 50, Turns: 1,
				Buff: BuffEffect{TargetDefense: -1, Chance: 0.1},
			},
		},
	}
	want := [3][3]int{
		{412, 257, 102},
		{597, 423, 269},
		{725, 459, 333},
	}
	assertPvPokeScoreGrid(t, quagsire, gastrodon, want)
}

func TestPvPokeOraclePinsirVersusCresselia(t *testing.T) {
	pinsir := Fighter{
		ID: "pinsir", Name: "Pinsir", Types: []string{"bug"},
		Attack: 141.3841383086, Defense: 110.0896254814, HP: 99,
		FastMove: Move{
			ID: "FURY_CUTTER", Name: "Fury Cutter", Type: "bug",
			Kind: FastMove, Power: 3, EnergyGain: 4, Turns: 1,
		},
		ChargedMoves: []Move{
			{
				ID: "CLOSE_COMBAT", Name: "Close Combat", Type: "fighting",
				Kind: ChargedMove, Power: 100, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{AttackerDefense: -2, Chance: 1},
			},
			{
				ID: "SUPER_POWER", Name: "Superpower", Type: "fighting",
				Kind: ChargedMove, Power: 85, EnergyCost: 40, Turns: 1,
				Buff: BuffEffect{AttackerAttack: -1, AttackerDefense: -1, Chance: 1},
			},
		},
	}
	cresselia := Fighter{
		ID: "cresselia", Name: "Cresselia", Types: []string{"psychic"},
		Attack: 94.6480015, Defense: 154.72397850000002, HP: 155,
		FastMove: Move{
			ID: "PSYCHO_CUT", Name: "Psycho Cut", Type: "psychic",
			Kind: FastMove, Power: 4, EnergyGain: 9, Turns: 2,
		},
		ChargedMoves: []Move{
			{
				ID: "GRASS_KNOT", Name: "Grass Knot", Type: "grass",
				Kind: ChargedMove, Power: 90, EnergyCost: 50, Turns: 1,
			},
			{
				ID: "MOONBLAST", Name: "Moonblast", Type: "fairy",
				Kind: ChargedMove, Power: 110, EnergyCost: 60, Turns: 1,
				Buff: BuffEffect{TargetAttack: -1, Chance: 0.1},
			},
		},
	}
	want := [3][3]int{
		{656, 325, 325},
		{813, 351, 351},
		{813, 757, 681},
	}
	assertPvPokeScoreGrid(t, pinsir, cresselia, want)
}

func TestPvPokeOracleDefersSelfDebuffForBestOpponentMove(t *testing.T) {
	pangoro := Fighter{
		ID: "pangoro", Name: "Pangoro", Types: []string{"fighting", "dark"},
		Attack: 136.5878345, Defense: 91.24747450000001, HP: 130,
		FastMove: Move{
			ID: "KARATE_CHOP", Name: "Karate Chop", Type: "fighting",
			Kind: FastMove, Power: 5, EnergyGain: 9, Turns: 2,
		},
		ChargedMoves: []Move{
			{
				ID: "CLOSE_COMBAT", Name: "Close Combat", Type: "fighting",
				Kind: ChargedMove, Power: 100, EnergyCost: 45, Turns: 1,
				Buff: BuffEffect{AttackerDefense: -2, Chance: 1},
			},
			{
				ID: "NIGHT_SLASH", Name: "Night Slash", Type: "dark",
				Kind: ChargedMove, Power: 50, EnergyCost: 35, Turns: 1,
				Buff: BuffEffect{AttackerAttack: 1, Chance: 0.125},
			},
		},
	}
	lickitung := Fighter{
		ID: "lickitung", Name: "Lickitung", Types: []string{"normal"},
		Attack: 99.97439815499999, Defense: 123.54559771999999, HP: 180,
		FastMove: Move{
			ID: "LICK", Name: "Lick", Type: "ghost",
			Kind: FastMove, Power: 3, EnergyGain: 3, Turns: 1,
		},
		ChargedMoves: []Move{
			{
				ID: "BODY_SLAM", Name: "Body Slam", Type: "normal",
				Kind: ChargedMove, Power: 55, EnergyCost: 35, Turns: 1,
			},
			{
				ID: "POWER_WHIP", Name: "Power Whip", Type: "grass",
				Kind: ChargedMove, Power: 90, EnergyCost: 50, Turns: 1,
			},
		},
	}
	result := simulatePvPokeCell(t, pangoro, lickitung, 0, 0)
	if result.Rating(0) != 715 || result.Fighters[0].HP != 56 ||
		result.Fighters[1].HP != 0 || result.Winner != 0 {
		t.Fatalf(
			"Pangoro vs Lickitung result = score %d, hp %d/%d, winner %d; want 715, 56/0, winner 0",
			result.Rating(0),
			result.Fighters[0].HP,
			result.Fighters[1].HP,
			result.Winner,
		)
	}
}

func TestPvPokeOracleSelfDebuffDeferWinnerFlip(t *testing.T) {
	moltres := Fighter{
		ID: "moltres_galarian", Name: "Moltres (Galarian)", Types: []string{"dark", "flying"},
		Attack: 152.01780279000002, Defense: 172.33354602, HP: 155,
		FastMove: Move{
			ID: "SUCKER_PUNCH", Name: "Sucker Punch", Type: "dark",
			Kind: FastMove, Power: 8, EnergyGain: 7, Turns: 2,
		},
		ChargedMoves: []Move{
			{
				ID: "FLY", Name: "Fly", Type: "flying",
				Kind: ChargedMove, Power: 80, EnergyCost: 45, Turns: 1,
			},
			{
				ID: "BRAVE_BIRD", Name: "Brave Bird", Type: "flying",
				Kind: ChargedMove, Power: 130, EnergyCost: 55, Turns: 1,
				Buff: BuffEffect{AttackerDefense: -3, Chance: 1},
			},
		},
	}
	dondozo := Fighter{
		ID: "dondozo", Name: "Dondozo", Types: []string{"water"},
		Attack: 137.4052281, Defense: 138.8440263, HP: 235,
		FastMove: Move{
			ID: "WATERFALL", Name: "Waterfall", Type: "water",
			Kind: FastMove, Power: 11, EnergyGain: 10, Turns: 3,
		},
		ChargedMoves: []Move{
			{
				ID: "SURF", Name: "Surf", Type: "water",
				Kind: ChargedMove, Power: 75, EnergyCost: 45, Turns: 1,
			},
			{
				ID: "OUTRAGE", Name: "Outrage", Type: "dragon",
				Kind: ChargedMove, Power: 110, EnergyCost: 60, Turns: 1,
			},
		},
	}
	result := simulatePvPokeCell(t, moltres, dondozo, 1, 1)
	if result.Rating(0) != 538 || result.Winner != 0 {
		t.Fatalf(
			"Moltres (Galarian) vs Dondozo result = score %d, winner %d; want 538, winner 0",
			result.Rating(0),
			result.Winner,
		)
	}
}

func simulatePvPokeCell(
	t *testing.T,
	focal Fighter,
	opponent Fighter,
	focalShields int,
	opponentShields int,
) BattleResult {
	t.Helper()
	config := DefaultBattleConfig()
	config.Shields = [2]int{focalShields, opponentShields}
	config.RecordTimeline = true
	result, err := Simulate([2]Fighter{focal, opponent}, config)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func assertPvPokeScoreGrid(
	t *testing.T,
	focal Fighter,
	opponent Fighter,
	want [3][3]int,
) {
	t.Helper()
	for focalShields := 0; focalShields <= 2; focalShields++ {
		for opponentShields := 0; opponentShields <= 2; opponentShields++ {
			result := simulatePvPokeCell(
				t,
				focal,
				opponent,
				focalShields,
				opponentShields,
			)
			if got := result.Rating(0); got != want[focalShields][opponentShields] {
				t.Errorf(
					"%s vs %s shields %d-%d score = %d, want %d; timeline=%#v",
					focal.ID,
					opponent.ID,
					focalShields,
					opponentShields,
					got,
					want[focalShields][opponentShields],
					result.Timeline,
				)
			}
		}
	}
}
