import { Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { NativeMethodologyPage } from '../features/tools/nativeMethodologyContent';

export const NativeMethodologyScreen = ({ content, onBack }: { content: NativeMethodologyPage; onBack: () => void }) => {
  const light = useColorScheme() === 'light'; const insets = useSafeAreaInsets();
  return <ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 8, paddingBottom: insets.bottom + 38 }]} style={[styles.root, light && styles.rootLight]} testID="native-methodology-screen">
    <View style={styles.topbar}><Pressable accessibilityLabel="Go back" onPress={onBack} style={[styles.back, light && styles.cardLight]}><Text style={[styles.backText, light && styles.textLight]}>‹</Text></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>{content.eyebrow}</Text><Text accessibilityRole="header" style={[styles.title, light && styles.textLight]}>{content.title}</Text></View></View><Text style={[styles.lead, light && styles.mutedLight]}>{content.description}</Text>
    {content.sections.map((section, index) => <View key={section.title} style={[styles.section, light && styles.cardLight]}><Text style={styles.sectionNumber}>0{index + 1}</Text><Text style={styles.eyebrow}>{section.eyebrow}</Text><Text style={[styles.sectionTitle, light && styles.textLight]}>{section.title}</Text>{section.paragraphs.map((paragraph) => <Text key={paragraph} style={[styles.body, light && styles.mutedLight]}>{paragraph}</Text>)}{section.bullets?.map((bullet) => <View key={bullet} style={styles.bulletRow}><Text style={styles.bullet}>•</Text><Text style={[styles.bulletText, light && styles.textLight]}>{bullet}</Text></View>)}</View>)}
    <Pressable accessibilityRole="button" onPress={onBack} style={styles.primary}><Text style={styles.primaryText}>Return to tools</Text></Pressable>
  </ScrollView>;
};
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: '#090d12' }, rootLight: { backgroundColor: '#eef4f7' }, content: { gap: 12, paddingHorizontal: 13 }, textLight: { color: '#14232a' }, mutedLight: { color: '#5d6f77' }, cardLight: { borderColor: '#c1cdd3', backgroundColor: '#fff' }, topbar: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 11 }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#43515a', borderRadius: 22, backgroundColor: '#171d22' }, backText: { marginTop: -4, color: '#fff', fontSize: 38 }, headerCopy: { minWidth: 0, flex: 1 }, eyebrow: { color: '#299cf5', fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, title: { color: '#fff', fontSize: 27, lineHeight: 32, fontWeight: '900' }, lead: { color: '#a8b5bc', fontSize: 13, lineHeight: 20 }, section: { overflow: 'hidden', borderWidth: 1, borderColor: '#34434b', borderRadius: 15, padding: 15, backgroundColor: '#151b20' }, sectionNumber: { position: 'absolute', right: 11, top: 7, color: '#273841', fontSize: 34, fontWeight: '900' }, sectionTitle: { marginTop: 5, marginBottom: 6, paddingRight: 30, color: '#fff', fontSize: 19, lineHeight: 24, fontWeight: '900' }, body: { marginTop: 5, color: '#abb8bf', fontSize: 13, lineHeight: 20 }, bulletRow: { flexDirection: 'row', gap: 8, marginTop: 8 }, bullet: { color: '#39c99d', fontSize: 15, fontWeight: '900' }, bulletText: { flex: 1, color: '#e3eaed', fontSize: 12, lineHeight: 18, fontWeight: '700' }, primary: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: '#168ced' }, primaryText: { color: '#fff', fontWeight: '900' } });

