import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { NativeActionMenu } from '../../components/NativeActionMenu';
import { NativeActionMenuAnchor } from '../../components/NativeActionMenuAnchor';
import { runtimeConfig } from '../../config/runtimeConfig';
import { useNativeSession } from '../../auth/NativeSessionContext';
import { useNativeCollectionSnapshotQuery } from '../../features/collection/collectionQueries';
import { hydrateNativeMaxCatalog } from '../../features/tools/nativeBattleModels';
import { useNativeMaxDataQuery, useNativeMovesDataQuery, useNativeToolCatalogQuery } from '../../features/tools/nativeToolQueries';
import { resolveNativeActionMenuDestination } from '../../navigation/nativeActionMenuNavigation';
import { NativeMaxScreen } from '../../screens/NativeMaxScreen';
export default function NativeMaxRoute() { const router = useRouter(); const session = useNativeSession(); const [menu, setMenu] = useState(false); const catalogQuery = useNativeToolCatalogQuery(); const movesQuery = useNativeMovesDataQuery(); const maxQuery = useNativeMaxDataQuery(); const snapshotQuery = useNativeCollectionSnapshotQuery(session.user?.user_id ?? null); const catalog = useMemo(() => hydrateNativeMaxCatalog(catalogQuery.data ?? [], maxQuery.data ?? [], movesQuery.data ?? []), [catalogQuery.data, maxQuery.data, movesQuery.data]); const error = [catalogQuery.error, movesQuery.error, maxQuery.error, snapshotQuery.error].find((value): value is Error => value instanceof Error)?.message ?? null; const navigate = (path: string) => { setMenu(false); const destination = resolveNativeActionMenuDestination(path, '/max'); if (destination.kind === 'current') return; if (destination.kind === 'native') { router.push(destination.pathname); return; } router.push({ pathname: '/web', params: { path: destination.path } }); }; return <><NativeMaxScreen assetBaseUrl={runtimeConfig.api.frontendAppUrl} catalog={catalog} error={error} instances={snapshotQuery.data?.instances} isLoading={catalogQuery.isPending || movesQuery.isPending || maxQuery.isPending || Boolean(session.user && snapshotQuery.isPending)} onBack={() => router.canGoBack() ? router.back() : router.replace('/native')} onOpenPokemon={(variantId) => router.push({ pathname: '/native/pokedex/[variantId]', params: { variantId } })} onRetry={() => { void catalogQuery.refetch(); void movesQuery.refetch(); void maxQuery.refetch(); if (session.user) void snapshotQuery.refetch(); }} signedIn={Boolean(session.user)} /><NativeActionMenuAnchor assetBaseUrl={runtimeConfig.api.frontendAppUrl} onPress={() => setMenu(true)} />{menu ? <NativeActionMenu assetBaseUrl={runtimeConfig.api.frontendAppUrl} onClose={() => setMenu(false)} onNavigate={navigate} visible /> : null}</>; }

