# Generated by Django 5.0.4 on 2024-07-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PokemonInstance',
            fields=[
                ('instance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pokemon_id', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('attack_iv', models.IntegerField(blank=True, null=True)),
                ('defense_iv', models.IntegerField(blank=True, null=True)),
                ('stamina_iv', models.IntegerField(blank=True, null=True)),
                ('shiny', models.BooleanField(default=False)),
                ('costume_id', models.IntegerField(blank=True, null=True)),
                ('lucky', models.BooleanField(default=False)),
                ('shadow', models.BooleanField(default=False)),
                ('purified', models.BooleanField(default=False)),
                ('fast_move_id', models.IntegerField(blank=True, null=True)),
                ('charged_move1_id', models.IntegerField(blank=True, null=True)),
                ('charged_move2_id', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('mirror', models.BooleanField(default=False)),
                ('pref_lucky', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('location_card', models.CharField(blank=True, max_length=255, null=True)),
                ('location_caught', models.CharField(blank=True, max_length=255, null=True)),
                ('friendship_level', models.IntegerField(blank=True, null=True)),
                ('date_caught', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.BigIntegerField(default=0)),
                ('is_unowned', models.BooleanField(default=False)),
                ('is_owned', models.BooleanField(default=False)),
                ('is_for_trade', models.BooleanField(default=False)),
                ('is_wanted', models.BooleanField(default=False)),
                ('not_trade_list', models.JSONField(default=dict)),
                ('not_wanted_list', models.JSONField(default=dict)),
                ('trace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.user')),
            ],
            options={
                'db_table': 'instances',
            },
        ),
    ]
