version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - gocritic
    - unconvert
    - unparam
    - prealloc
    - bodyclose
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
