CREATE SCHEMA IF NOT EXISTS pokemon_catalog;

CREATE TABLE IF NOT EXISTS pokemon_catalog.schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.types (
  type_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  icon_url TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.evolution_items (
  item_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.cp_multipliers (
  level_id DOUBLE PRECISION PRIMARY KEY,
  multiplier DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon (
  pokemon_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  pokedex_number INTEGER,
  image_url TEXT,
  image_url_shiny TEXT,
  sprite_url TEXT,
  attack INTEGER,
  defense INTEGER,
  stamina INTEGER,
  type_1_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  type_2_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  gender_rate TEXT,
  rarity TEXT,
  form TEXT,
  generation INTEGER,
  available BOOLEAN,
  shiny_available BOOLEAN,
  shiny_rarity TEXT,
  date_available TEXT,
  date_shiny_available TEXT,
  female_unique BOOLEAN
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.backgrounds (
  background_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  image_url TEXT,
  date TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.moves (
  move_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  type_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  raid_power INTEGER,
  pvp_power INTEGER,
  raid_energy INTEGER,
  pvp_energy INTEGER,
  raid_cooldown INTEGER,
  pvp_turns INTEGER,
  is_fast BOOLEAN NOT NULL DEFAULT FALSE,
  fusion_id INTEGER,
  shadow BOOLEAN,
  purified BOOLEAN,
  apex BOOLEAN
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.costume_pokemon (
  costume_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id),
  costume_name TEXT,
  shiny_available BOOLEAN,
  date_available TEXT,
  date_shiny_available TEXT,
  image_url_costume TEXT,
  image_url_shiny_costume TEXT,
  image_url_costume_female TEXT,
  image_url_shiny_costume_female TEXT
);

CREATE INDEX IF NOT EXISTS idx_costume_pokemon_pokemon_id
  ON pokemon_catalog.costume_pokemon(pokemon_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.female_pokemon (
  pokemon_id INTEGER PRIMARY KEY REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  image_url TEXT,
  shiny_image_url TEXT,
  shadow_image_url TEXT,
  shiny_shadow_image_url TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.shadow_pokemon (
  id INTEGER PRIMARY KEY,
  -- Some upstream shadow rows intentionally arrive before their base Pokemon
  -- metadata. Keep those source records for audit instead of dropping them.
  pokemon_id INTEGER NOT NULL,
  -- Legacy source values can be 1, NULL, or an empty string. Preserve that
  -- current browser contract during cutover; a later schema revision can add
  -- normalized boolean columns without changing the served payload.
  shiny_available TEXT,
  apex TEXT,
  date_available TEXT,
  date_shiny_available TEXT,
  image_url_shadow TEXT,
  image_url_shiny_shadow TEXT,
  shiny_rarity TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.fusion_pokemon (
  fusion_id INTEGER PRIMARY KEY,
  base_pokemon_id1 INTEGER REFERENCES pokemon_catalog.pokemon(pokemon_id),
  base_pokemon_id2 INTEGER REFERENCES pokemon_catalog.pokemon(pokemon_id),
  name TEXT,
  pokedex_number INTEGER,
  image_url TEXT,
  image_url_shiny TEXT,
  sprite_url TEXT,
  attack INTEGER,
  defense INTEGER,
  stamina INTEGER,
  type_1_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  type_2_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  generation INTEGER,
  available BOOLEAN,
  shiny_available BOOLEAN,
  shiny_rarity TEXT,
  date_available TEXT,
  date_shiny_available TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.mega_evolution (
  id INTEGER PRIMARY KEY,
  pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  mega_energy_cost INTEGER,
  attack INTEGER,
  defense INTEGER,
  stamina INTEGER,
  image_url TEXT,
  image_url_shiny TEXT,
  sprite_url TEXT,
  -- The source has 1, NULL, and one historical "None" value.
  primal TEXT,
  form TEXT,
  type_1_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  type_2_id INTEGER REFERENCES pokemon_catalog.types(type_id),
  date_available TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.max_pokemon (
  pokemon_id INTEGER PRIMARY KEY REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  dynamax BOOLEAN,
  gigantamax BOOLEAN,
  dynamax_release_date TEXT,
  gigantamax_release_date TEXT,
  gigantamax_image_url TEXT,
  shiny_gigantamax_image_url TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon_sizes (
  -- Size metadata can arrive ahead of an unreleased base Pokemon record.
  pokemon_id INTEGER PRIMARY KEY,
  pokedex_height DOUBLE PRECISION NOT NULL,
  pokedex_weight DOUBLE PRECISION NOT NULL,
  height_standard_deviation DOUBLE PRECISION NOT NULL,
  weight_standard_deviation DOUBLE PRECISION NOT NULL,
  height_xxs_threshold DOUBLE PRECISION NOT NULL,
  height_xs_threshold DOUBLE PRECISION NOT NULL,
  height_xl_threshold DOUBLE PRECISION NOT NULL,
  height_xxl_threshold DOUBLE PRECISION NOT NULL,
  weight_xxs_threshold DOUBLE PRECISION NOT NULL,
  weight_xs_threshold DOUBLE PRECISION NOT NULL,
  weight_xl_threshold DOUBLE PRECISION NOT NULL,
  weight_xxl_threshold DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon_backgrounds (
  -- Preserve provisional upstream links for data-quality auditing.
  pokemon_id INTEGER NOT NULL,
  background_id INTEGER NOT NULL REFERENCES pokemon_catalog.backgrounds(background_id) ON DELETE CASCADE,
  costume_id INTEGER REFERENCES pokemon_catalog.costume_pokemon(costume_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pokemon_backgrounds_pokemon_id
  ON pokemon_catalog.pokemon_backgrounds(pokemon_id);

CREATE INDEX IF NOT EXISTS idx_pokemon_backgrounds_background_id
  ON pokemon_catalog.pokemon_backgrounds(background_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon_evolutions (
  evolution_id INTEGER PRIMARY KEY,
  pokemon_id INTEGER NOT NULL,
  evolves_to INTEGER,
  candies_needed INTEGER,
  -- Legacy source values include 1, NULL, and an empty string.
  trade_discount TEXT,
  item_id INTEGER,
  other TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon_moves (
  id INTEGER PRIMARY KEY,
  move_id INTEGER NOT NULL REFERENCES pokemon_catalog.moves(move_id) ON DELETE CASCADE,
  -- Move data may precede an upstream Pokemon catalog entry.
  pokemon_id INTEGER NOT NULL,
  legacy BOOLEAN
);

CREATE INDEX IF NOT EXISTS idx_pokemon_moves_pokemon_id
  ON pokemon_catalog.pokemon_moves(pokemon_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.pokemon_cp_stats (
  -- CP rows are retained even for provisional Pokemon IDs; the serving layer
  -- only emits rows whose base record is present in the published catalog.
  pokemon_id INTEGER NOT NULL,
  level_id DOUBLE PRECISION NOT NULL REFERENCES pokemon_catalog.cp_multipliers(level_id),
  cp INTEGER,
  hp INTEGER,
  PRIMARY KEY (pokemon_id, level_id)
);

CREATE INDEX IF NOT EXISTS idx_pokemon_cp_stats_pokemon_id
  ON pokemon_catalog.pokemon_cp_stats(pokemon_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.shadow_costume_pokemon (
  id INTEGER PRIMARY KEY,
  shadow_id INTEGER NOT NULL REFERENCES pokemon_catalog.shadow_pokemon(id) ON DELETE CASCADE,
  costume_id INTEGER NOT NULL REFERENCES pokemon_catalog.costume_pokemon(costume_id) ON DELETE CASCADE,
  date_available TEXT,
  date_shiny_available TEXT,
  image_url_shadow_costume TEXT,
  image_url_shiny_shadow_costume TEXT,
  image_url_female_shadow_costume TEXT,
  image_url_female_shiny_shadow_costume TEXT
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.mega_cp_stats (
  mega_id INTEGER NOT NULL REFERENCES pokemon_catalog.mega_evolution(id) ON DELETE CASCADE,
  level_id DOUBLE PRECISION NOT NULL REFERENCES pokemon_catalog.cp_multipliers(level_id),
  cp INTEGER,
  hp INTEGER,
  PRIMARY KEY (mega_id, level_id)
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.fusion_cp_stats (
  fusion_id INTEGER NOT NULL REFERENCES pokemon_catalog.fusion_pokemon(fusion_id) ON DELETE CASCADE,
  level_id DOUBLE PRECISION NOT NULL REFERENCES pokemon_catalog.cp_multipliers(level_id),
  cp INTEGER,
  hp INTEGER,
  PRIMARY KEY (fusion_id, level_id)
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.fusion_moveset (
  fusion_id INTEGER NOT NULL REFERENCES pokemon_catalog.fusion_pokemon(fusion_id) ON DELETE CASCADE,
  move_id INTEGER NOT NULL REFERENCES pokemon_catalog.moves(move_id) ON DELETE CASCADE,
  legacy BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (fusion_id, move_id)
);

CREATE INDEX IF NOT EXISTS idx_fusion_moveset_move_id
  ON pokemon_catalog.fusion_moveset(move_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.crown_forms (
  id INTEGER PRIMARY KEY,
  base_pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  crown_pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  display_form TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  UNIQUE(base_pokemon_id, crown_pokemon_id)
);

CREATE TABLE IF NOT EXISTS pokemon_catalog.fusion_background_combo_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fusion_id INTEGER NOT NULL REFERENCES pokemon_catalog.fusion_pokemon(fusion_id) ON DELETE CASCADE,
  member1_background_id INTEGER NOT NULL REFERENCES pokemon_catalog.backgrounds(background_id),
  member2_background_id INTEGER NOT NULL REFERENCES pokemon_catalog.backgrounds(background_id),
  combo_background_id INTEGER NOT NULL REFERENCES pokemon_catalog.backgrounds(background_id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  UNIQUE (fusion_id, member1_background_id, member2_background_id, combo_background_id)
);

CREATE INDEX IF NOT EXISTS idx_fusion_bg_combo_rules_fusion_id
  ON pokemon_catalog.fusion_background_combo_rules(fusion_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.raid_bosses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  name TEXT,
  form TEXT,
  type TEXT,
  boosted_weather TEXT,
  max_boosted_cp INTEGER,
  max_unboosted_cp INTEGER,
  min_boosted_cp INTEGER,
  min_unboosted_cp INTEGER,
  possible_shiny BOOLEAN,
  tier TEXT,
  costume_id INTEGER REFERENCES pokemon_catalog.costume_pokemon(costume_id),
  shield_count INTEGER CHECK (shield_count IS NULL OR shield_count > 0)
);

CREATE INDEX IF NOT EXISTS idx_raid_bosses_pokemon_id
  ON pokemon_catalog.raid_bosses(pokemon_id);

CREATE TABLE IF NOT EXISTS pokemon_catalog.catalog_releases (
  release_id TEXT PRIMARY KEY,
  source_sha256 TEXT NOT NULL,
  source_label TEXT NOT NULL,
  table_counts JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activated_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS catalog_releases_one_active
  ON pokemon_catalog.catalog_releases ((is_active))
  WHERE is_active;
