CREATE TABLE IF NOT EXISTS pokemon_catalog.max_battle_tiers (
  tier_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('standard', 'legendary', 'gigantamax')),
  boss_hp INTEGER NOT NULL CHECK (boss_hp > 0),
  default_trainers INTEGER NOT NULL CHECK (default_trainers > 0),
  max_trainers INTEGER NOT NULL CHECK (max_trainers >= default_trainers),
  battle_seconds INTEGER NOT NULL DEFAULT 360 CHECK (battle_seconds > 0),
  enrage_seconds INTEGER NOT NULL DEFAULT 360 CHECK (enrage_seconds > 0),
  subgroup_size INTEGER NOT NULL DEFAULT 4 CHECK (subgroup_size > 0),
  meter_orb_energy INTEGER NOT NULL DEFAULT 10 CHECK (meter_orb_energy >= 0)
);

INSERT INTO pokemon_catalog.max_battle_tiers (
  tier_key,
  label,
  kind,
  boss_hp,
  default_trainers,
  max_trainers,
  battle_seconds,
  enrage_seconds,
  subgroup_size,
  meter_orb_energy
) VALUES
  ('one-star', 'One-star Max', 'standard', 1700, 1, 4, 360, 360, 4, 10),
  ('two-star', 'Two-star Max', 'standard', 5000, 1, 4, 360, 360, 4, 10),
  ('three-star', 'Three-star Max', 'standard', 10000, 2, 4, 360, 360, 4, 10),
  ('legendary', 'Legendary Max', 'legendary', 17500, 4, 4, 360, 360, 4, 10),
  ('gigantamax', 'Six-star Gigantamax', 'gigantamax', 90000, 12, 100, 360, 360, 4, 10)
ON CONFLICT (tier_key) DO UPDATE SET
  label = EXCLUDED.label,
  kind = EXCLUDED.kind,
  boss_hp = EXCLUDED.boss_hp,
  default_trainers = EXCLUDED.default_trainers,
  max_trainers = EXCLUDED.max_trainers,
  battle_seconds = EXCLUDED.battle_seconds,
  enrage_seconds = EXCLUDED.enrage_seconds,
  subgroup_size = EXCLUDED.subgroup_size,
  meter_orb_energy = EXCLUDED.meter_orb_energy;

CREATE TABLE IF NOT EXISTS pokemon_catalog.max_battle_profiles (
  profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_id INTEGER NOT NULL REFERENCES pokemon_catalog.pokemon(pokemon_id) ON DELETE CASCADE,
  variant_kind TEXT NOT NULL CHECK (variant_kind IN ('dynamax', 'gigantamax', 'special')),
  form TEXT,
  tier_key TEXT NOT NULL REFERENCES pokemon_catalog.max_battle_tiers(tier_key),
  label_override TEXT,
  boss_hp_override INTEGER CHECK (boss_hp_override IS NULL OR boss_hp_override > 0),
  default_trainers_override INTEGER CHECK (
    default_trainers_override IS NULL OR default_trainers_override > 0
  ),
  max_trainers_override INTEGER CHECK (
    max_trainers_override IS NULL OR max_trainers_override > 0
  ),
  battle_seconds_override INTEGER CHECK (
    battle_seconds_override IS NULL OR battle_seconds_override > 0
  ),
  enrage_seconds_override INTEGER CHECK (
    enrage_seconds_override IS NULL OR enrage_seconds_override > 0
  ),
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  priority INTEGER NOT NULL DEFAULT 0,
  source_name TEXT,
  source_url TEXT,
  notes TEXT,
  CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at),
  CHECK (
    max_trainers_override IS NULL
    OR default_trainers_override IS NULL
    OR max_trainers_override >= default_trainers_override
  )
);

CREATE INDEX IF NOT EXISTS idx_max_battle_profiles_pokemon_id
  ON pokemon_catalog.max_battle_profiles(pokemon_id);

CREATE INDEX IF NOT EXISTS idx_max_battle_profiles_active_window
  ON pokemon_catalog.max_battle_profiles(starts_at, ends_at)
  WHERE starts_at IS NOT NULL OR ends_at IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS max_battle_profiles_one_default
  ON pokemon_catalog.max_battle_profiles (
    pokemon_id,
    variant_kind,
    COALESCE(LOWER(form), '')
  )
  WHERE is_default IS TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS max_battle_profiles_unique_entry
  ON pokemon_catalog.max_battle_profiles (
    pokemon_id,
    variant_kind,
    COALESCE(LOWER(form), ''),
    tier_key,
    COALESCE(starts_at, '-infinity'::TIMESTAMPTZ),
    COALESCE(ends_at, 'infinity'::TIMESTAMPTZ)
  );

-- Start with the high-confidence encounter that motivated this schema. Future
-- event windows can be added without changing frontend heuristics.
INSERT INTO pokemon_catalog.max_battle_profiles (
  profile_id,
  pokemon_id,
  variant_kind,
  form,
  tier_key,
  is_default,
  priority,
  source_name,
  source_url,
  notes
)
SELECT
  profile.profile_id,
  profile.pokemon_id,
  profile.variant_kind,
  profile.form,
  profile.tier_key,
  profile.is_default,
  profile.priority,
  profile.source_name,
  profile.source_url,
  profile.notes
FROM (
  VALUES
    (
      100001,
      1,
      'dynamax',
      NULL::TEXT,
      'one-star',
      TRUE,
      100,
      'Pokemon GO Hub Bulbasaur database',
      'https://db.pokemongohub.net/pokemon/001',
      'Dynamax Bulbasaur is documented as a one-star Max Battle.'
    ),
    (
      100002,
      1,
      'dynamax',
      NULL::TEXT,
      'three-star',
      FALSE,
      10,
      'PokeGoNexus event override support',
      NULL::TEXT,
      'Available for promoted events; select only when the Power Spot shows three stars.'
    )
) AS profile (
  profile_id,
  pokemon_id,
  variant_kind,
  form,
  tier_key,
  is_default,
  priority,
  source_name,
  source_url,
  notes
)
WHERE EXISTS (
  SELECT 1
  FROM pokemon_catalog.pokemon
  WHERE pokemon.pokemon_id = profile.pokemon_id
)
ON CONFLICT (profile_id) DO UPDATE SET
  pokemon_id = EXCLUDED.pokemon_id,
  variant_kind = EXCLUDED.variant_kind,
  form = EXCLUDED.form,
  tier_key = EXCLUDED.tier_key,
  is_default = EXCLUDED.is_default,
  priority = EXCLUDED.priority,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url,
  notes = EXCLUDED.notes;

SELECT setval(
  pg_get_serial_sequence('pokemon_catalog.max_battle_profiles', 'profile_id'),
  GREATEST(
    (SELECT COALESCE(MAX(profile_id), 1) FROM pokemon_catalog.max_battle_profiles),
    1
  ),
  TRUE
);

-- Existing production catalogs predate the provisioning default privilege.
-- Repair their least-privileged API role during this migration when present.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'pokemon_catalog_reader'
  ) THEN
    EXECUTE 'GRANT USAGE ON SCHEMA pokemon_catalog TO pokemon_catalog_reader';
    EXECUTE 'GRANT SELECT ON pokemon_catalog.max_battle_tiers TO pokemon_catalog_reader';
    EXECUTE 'GRANT SELECT ON pokemon_catalog.max_battle_profiles TO pokemon_catalog_reader';
  END IF;
END $$;
