ALTER TABLE pokemon_catalog.pvp_rankings
  ADD COLUMN IF NOT EXISTS matchups JSONB NOT NULL DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS counters JSONB NOT NULL DEFAULT '[]'::JSONB,
  ADD COLUMN IF NOT EXISTS move_usage JSONB NOT NULL DEFAULT '[]'::JSONB;

