#!/usr/bin/env bash

# Shared helpers for the explicit SQLite-to-PostgreSQL API cutover. The reader
# file is generated by provision-postgres.sh and contains only the restricted
# catalog account used by the running Pokemon API.

catalog_load_reader_settings() {
  local reader_env_file="$1"

  [[ -r "${reader_env_file}" ]] || {
    echo "catalog cutover error: reader settings are not readable: ${reader_env_file}" >&2
    return 1
  }

  set -a
  # shellcheck disable=SC1090
  source "${reader_env_file}"
  set +a

  for required in CATALOG_DB_DRIVER CATALOG_DATABASE_URL; do
    [[ -n "${!required:-}" ]] || {
      echo "catalog cutover error: ${required} is missing from ${reader_env_file}" >&2
      return 1
    }
  done

  [[ "${CATALOG_DB_DRIVER}" == "postgres" || "${CATALOG_DB_DRIVER}" == "postgresql" ]] || {
    echo "catalog cutover error: reader settings must select PostgreSQL" >&2
    return 1
  }
}

catalog_write_postgres_runtime_env() {
  local app_env_file="$1"
  local backup_file="$2"
  local tmp_file=""

  [[ -f "${app_env_file}" ]] || {
    echo "catalog cutover error: Pokemon runtime environment is missing: ${app_env_file}" >&2
    return 1
  }
  [[ -n "${CATALOG_DB_DRIVER:-}" && -n "${CATALOG_DATABASE_URL:-}" ]] || {
    echo "catalog cutover error: load reader settings before writing runtime configuration" >&2
    return 1
  }
  [[ "${CATALOG_DATABASE_URL}" != *$'\n'* && "${CATALOG_DATABASE_URL}" != *$'\r'* ]] || {
    echo "catalog cutover error: catalog database URL contains a line break" >&2
    return 1
  }

  mkdir -p "$(dirname "${backup_file}")"
  cp -a "${app_env_file}" "${backup_file}"

  tmp_file="$(mktemp "${app_env_file}.postgres-cutover.XXXXXX")"
  trap 'rm -f "${tmp_file}"' RETURN
  awk '!/^(CATALOG_DB_DRIVER|CATALOG_DATABASE_URL)=/' "${app_env_file}" > "${tmp_file}"
  {
    printf '\n# Pokemon catalog source. Managed by the PostgreSQL cutover workflow.\n'
    printf 'CATALOG_DB_DRIVER=%s\n' "${CATALOG_DB_DRIVER}"
    printf 'CATALOG_DATABASE_URL=%s\n' "${CATALOG_DATABASE_URL}"
  } >> "${tmp_file}"
  chmod 600 "${tmp_file}"
  mv "${tmp_file}" "${app_env_file}"
  trap - RETURN
}

catalog_restore_runtime_env() {
  local backup_file="$1"
  local app_env_file="$2"

  [[ -f "${backup_file}" ]] || {
    echo "catalog cutover error: runtime environment backup is missing: ${backup_file}" >&2
    return 1
  }
  install -m 600 "${backup_file}" "${app_env_file}"
}
