import type { InstancesMap } from '@pokemongonexus/shared-contracts/instances';
import {
  filterInstancesByOwnership,
  toInstanceListItems,
} from '../../../../src/features/instances/instanceReadModels';

describe('instanceReadModels', () => {
  const fixture: InstancesMap = {
    i1: {
      variant_id: 'v-001',
      pokemon_id: 1,
      nickname: null,
      cp: null,
      level: null,
      attack_iv: null,
      defense_iv: null,
      stamina_iv: null,
      shiny: false,
      costume_id: null,
      lucky: false,
      shadow: false,
      purified: false,
      fast_move_id: null,
      charged_move1_id: null,
      charged_move2_id: null,
      weight: null,
      height: null,
      gender: null,
      mega: false,
      mega_form: null,
      is_mega: false,
      dynamax: false,
      gigantamax: false,
      crown: false,
      max_attack: null,
      max_guard: null,
      max_spirit: null,
      is_fused: false,
      fusion: null,
      fusion_form: null,
      fused_with: null,
      is_traded: false,
      traded_date: null,
      original_trainer_id: null,
      original_trainer_name: null,
      is_caught: true,
      is_for_trade: false,
      is_wanted: false,
      most_wanted: false,
      caught_tags: null,
      trade_tags: null,
      wanted_tags: null,
      not_trade_list: null,
      not_wanted_list: null,
      trade_filters: null,
      wanted_filters: null,
      mirror: false,
      pref_lucky: false,
      registered: true,
      favorite: false,
      disabled: false,
      pokeball: null,
      location_card: null,
      location_caught: null,
      date_caught: null,
      date_added: '2026-01-01T00:00:00.000Z',
      last_update: 1,
    },
    i2: {
      variant_id: 'v-001',
      pokemon_id: 1,
      nickname: null,
      cp: null,
      level: null,
      attack_iv: null,
      defense_iv: null,
      stamina_iv: null,
      shiny: false,
      costume_id: null,
      lucky: false,
      shadow: false,
      purified: false,
      fast_move_id: null,
      charged_move1_id: null,
      charged_move2_id: null,
      weight: null,
      height: null,
      gender: null,
      mega: false,
      mega_form: null,
      is_mega: false,
      dynamax: false,
      gigantamax: false,
      crown: false,
      max_attack: null,
      max_guard: null,
      max_spirit: null,
      is_fused: false,
      fusion: null,
      fusion_form: null,
      fused_with: null,
      is_traded: false,
      traded_date: null,
      original_trainer_id: null,
      original_trainer_name: null,
      is_caught: false,
      is_for_trade: true,
      is_wanted: true,
      most_wanted: false,
      caught_tags: null,
      trade_tags: null,
      wanted_tags: null,
      not_trade_list: null,
      not_wanted_list: null,
      trade_filters: null,
      wanted_filters: null,
      mirror: false,
      pref_lucky: false,
      registered: true,
      favorite: false,
      disabled: false,
      pokeball: null,
      location_card: null,
      location_caught: null,
      date_caught: null,
      date_added: '2026-01-01T00:00:00.000Z',
      last_update: 1,
    },
  };

  it('maps instances into sorted list entries', () => {
    const list = toInstanceListItems(fixture);
    expect(list).toHaveLength(2);
    expect(list[0]?.instanceId).toBe('i1');
    expect(list[1]?.isForTrade).toBe(true);
  });

  it('filters caught/trade/wanted ownership modes', () => {
    const list = toInstanceListItems(fixture);
    expect(filterInstancesByOwnership(list, 'caught').map((entry) => entry.instanceId)).toEqual(['i1']);
    expect(filterInstancesByOwnership(list, 'trade').map((entry) => entry.instanceId)).toEqual(['i2']);
    expect(filterInstancesByOwnership(list, 'wanted').map((entry) => entry.instanceId)).toEqual(['i2']);
  });
});
